"use client";

import { useEffect, useRef } from "react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { TrendingUp, Wallet, Flame, ArrowRight } from "lucide-react";

gsap.registerPlugin(ScrollTrigger);

const facts = [
  { label: "Ticker", value: "RARE" },
  { label: "Blockchain", value: "Solana" },
  { label: "Standard", value: "SPL" },
  { label: "Launch", value: "Proof · Bonding Curve" },
];

const stats = [
  { value: "1B", label: "Max Supply", sub: "Fixed forever" },
  { value: "0%", label: "Team Allocation", sub: "No insider cut" },
  { value: "0%", label: "Presale", sub: "No private round" },
  { value: "100%", label: "Public Curve", sub: "Every token" },
];

const comparison = [
  { field: "Team allocation", typical: "Set aside pre-launch, 5–15%", rarecoin: "None — via bonding curve" },
  { field: "Vesting schedule", typical: "Cliff + 1–4yr linear unlock", rarecoin: "Not applicable" },
  { field: "Presale / private round", typical: "Common, often discounted", rarecoin: "None" },
  { field: "Initial liquidity", typical: "Team- or investor-funded", rarecoin: "Formed by the bonding curve" },
  { field: "Supply at launch", typical: "Partial — rest locked/vesting", rarecoin: "100% tradable from trade one" },
];

const feeFlow = [
  { icon: TrendingUp, label: "Trading Fees", description: "Generated by activity on Proof's bonding curve." },
  { icon: Wallet, label: "Creator Fee Share", description: "A disclosed share paid to the creator wallet." },
  { icon: Flame, label: "Rewards & Burn", description: "Funds contributor rewards and buyback-and-burn events." },
];

// ── Distribution graphic ───────────────────────────────────────────────────────
function DistributionGraphic() {
  return (
    <svg viewBox="0 0 320 320" fill="none" className="w-full max-w-xs mx-auto" aria-hidden="true">
      {/* Outer ring — full circle = 100% public */}
      <circle cx="160" cy="160" r="130" stroke="#3355ff" strokeWidth="28" opacity="0.15" />
      <circle
        cx="160" cy="160" r="130"
        stroke="#3355ff" strokeWidth="28"
        strokeDasharray="817 0"
        strokeLinecap="round"
        transform="rotate(-90 160 160)"
        opacity="0.9"
      />

      {/* Inner ring accent */}
      <circle cx="160" cy="160" r="95" stroke="#7b3fe4" strokeWidth="1" strokeDasharray="4 5" opacity="0.25" />

      {/* Center text */}
      <text x="160" y="148" textAnchor="middle" fontSize="42" fontWeight="700" fill="white" fontFamily="Space Grotesk, sans-serif">100%</text>
      <text x="160" y="172" textAnchor="middle" fontSize="11" fill="white" opacity="0.4" fontFamily="Space Grotesk, sans-serif" letterSpacing="2">PUBLIC</text>

      {/* Single label */}
      <rect x="88" y="198" width="144" height="30" rx="15" fill="#3355ff" opacity="0.18" />
      <text x="160" y="218" textAnchor="middle" fontSize="11" fontWeight="600" fill="#3355ff" fontFamily="Space Grotesk, sans-serif">Bonding Curve Only</text>

      {/* Tick marks */}
      {Array.from({ length: 24 }).map((_, i) => {
        const a = (i / 24) * Math.PI * 2 - Math.PI / 2;
        const cos = Math.cos(a).toFixed(4);
        const sin = Math.sin(a).toFixed(4);
        return (
          <line key={i}
            x1={160 + 148 * Number(cos)} y1={160 + 148 * Number(sin)}
            x2={160 + 156 * Number(cos)} y2={160 + 156 * Number(sin)}
            stroke="white" strokeWidth="1.5" opacity="0.15"
          />
        );
      })}
    </svg>
  );
}

// ── Section ────────────────────────────────────────────────────────────────────
export default function Tokenomics() {
  const sectionRef = useRef<HTMLElement>(null);

  useEffect(() => {
    const ctx = gsap.context(() => {
      const trigger = { trigger: sectionRef.current, start: "top 75%" };

      gsap.fromTo(".tok-heading",
        { opacity: 0, y: 32 },
        { opacity: 1, y: 0, duration: 0.7, ease: "power3.out", scrollTrigger: trigger }
      );
      gsap.fromTo(".tok-fact",
        { opacity: 0, y: 16 },
        { opacity: 1, y: 0, duration: 0.5, stagger: 0.06, ease: "power3.out", scrollTrigger: trigger }
      );
      gsap.fromTo(".tok-stat",
        { opacity: 0, y: 36 },
        { opacity: 1, y: 0, duration: 0.6, stagger: 0.1, ease: "power3.out", scrollTrigger: trigger }
      );
      gsap.fromTo(".tok-graphic",
        { opacity: 0, scale: 0.88 },
        { opacity: 1, scale: 1, duration: 0.9, ease: "power3.out", scrollTrigger: trigger }
      );
      gsap.fromTo(".tok-row",
        { opacity: 0, x: -16 },
        { opacity: 1, x: 0, duration: 0.5, stagger: 0.07, ease: "power3.out",
          scrollTrigger: { trigger: ".tok-row", start: "top 85%" } }
      );
      gsap.fromTo(".tok-flow",
        { opacity: 0, y: 24 },
        { opacity: 1, y: 0, duration: 0.6, stagger: 0.12, ease: "power3.out",
          scrollTrigger: { trigger: ".tok-flow", start: "top 88%" } }
      );
    }, sectionRef);

    return () => ctx.revert();
  }, []);

  return (
    <section ref={sectionRef} id="tokenomics" className="bg-[#0b0c12] px-6 py-28 lg:px-16">
      <div className="mx-auto max-w-7xl flex flex-col gap-20">

        {/* Heading */}
        <div className="flex flex-col gap-8">
          <div className="tok-heading flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
            <div className="flex flex-col gap-3">
              <span className="text-xs font-semibold uppercase tracking-widest text-[#3355ff]">
                Tokenomics
              </span>
              <h2 className="font-heading text-4xl font-bold leading-tight text-white md:text-5xl">
                Nothing hidden<br />in the numbers.
              </h2>
            </div>
            <p className="max-w-sm text-sm leading-relaxed text-white/40 md:text-right">
              No allocation pools, no vesting cliffs, no team tranche. Every RARE token enters circulation the same way through the public bonding curve.
            </p>
          </div>

          {/* Token facts strip */}
          <div className="flex flex-wrap items-center gap-2">
            {facts.map(({ label, value }) => (
              <div
                key={label}
                className="tok-fact flex items-center gap-2 rounded-full border border-white/8 bg-white/[0.03] px-4 py-2 text-xs"
              >
                <span className="text-white/35">{label}</span>
                <span className="font-semibold text-white/80">{value}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Stats row */}
        <div className="grid grid-cols-2 gap-px bg-white/8 rounded-2xl overflow-hidden md:grid-cols-4">
          {stats.map(({ value, label, sub }) => (
            <div key={label} className="tok-stat flex flex-col gap-1.5 bg-[#0b0c12] px-8 py-10">
              <span className="font-heading text-5xl font-bold text-white">{value}</span>
              <span className="text-sm font-semibold text-white/70">{label}</span>
              <span className="text-xs text-white/30">{sub}</span>
            </div>
          ))}
        </div>

        {/* Graphic + comparison */}
        <div className="grid grid-cols-1 gap-16 md:grid-cols-2 md:items-center">

          {/* Distribution donut */}
          <div className="tok-graphic flex flex-col items-center gap-4">
            <DistributionGraphic />
            <p className="max-w-[220px] text-center text-xs leading-relaxed text-white/30">
              No team, presale, or treasury slice — the full circle is the public curve.
            </p>
          </div>

          {/* Comparison table */}
          <div className="flex flex-col gap-2">
            <div className="mb-4 grid grid-cols-[1.1fr_1fr_1fr] gap-3 text-xs font-semibold uppercase tracking-widest text-white/30">
              <span>Field</span>
              <span>Typical Presale</span>
              <span className="text-[#3355ff]">Rarecoin</span>
            </div>

            {comparison.map(({ field, typical, rarecoin }) => (
              <div
                key={field}
                className="tok-row grid grid-cols-[1.1fr_1fr_1fr] gap-3 rounded-xl px-4 py-3.5 text-sm transition-colors hover:bg-white/4"
              >
                <span className="font-medium text-white/70">{field}</span>
                <span className="text-white/35">{typical}</span>
                <span className="text-white/90">{rarecoin}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Where the fees go */}
        <div className="flex flex-col gap-8">
          <div className="flex flex-col gap-3">
            <span className="text-xs font-semibold uppercase tracking-widest text-[#3355ff]">
              Sustainability
            </span>
            <h3 className="font-heading text-2xl font-bold text-white md:text-3xl">
              Where the fees go.
            </h3>
          </div>

          <div className="flex flex-col items-stretch gap-3 md:flex-row md:items-center">
            {feeFlow.map(({ icon: Icon, label, description }, i) => (
              <div key={label} className="flex flex-1 items-center gap-3">
                <div className="tok-flow flex flex-1 flex-col gap-3 rounded-2xl border border-white/8 bg-white/[0.03] p-6">
                  <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#3355ff]/12 text-[#7ea1ff]">
                    <Icon size={18} strokeWidth={1.75} />
                  </div>
                  <div className="flex flex-col gap-1">
                    <span className="font-heading text-base font-bold text-white">{label}</span>
                    <span className="text-xs leading-relaxed text-white/40">{description}</span>
                  </div>
                </div>
                {i < feeFlow.length - 1 && (
                  <ArrowRight size={18} className="hidden shrink-0 text-white/15 md:block" />
                )}
              </div>
            ))}
          </div>
        </div>

      </div>
    </section>
  );
}
